global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "Homies"
    metrics_path: "/metrics"
    static_configs:
      - targets: ['localhost:8001']
      - targets: ['localhost:8002']
      - targets: ['localhost:8003']
      